export const styles = {
    container: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center', 
        minHeight: '100vh', 
        padding: '20px',
        backgroundColor: '#e0f7fa',
    },
    title: {
        fontSize: '2.5rem', 
        color: '#007BFF',
        marginBottom: '20px', 
    },
    form: {
        display: 'flex',
        flexDirection: 'column',
        width: '300px',
    },
    input: {
        margin: '10px 0',
        padding: '10px',
        borderRadius: '4px',
        border: '1px solid #ccc',
        fontSize: '1rem', 
    },
    button: {
        backgroundColor: '#007BFF', 
        color: 'white',
        padding: '10px',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
        marginTop: '10px',
        transition: 'background-color 0.3s', 
    },
    toggleButton: {
        backgroundColor: 'transparent', 
        color: '#007BFF', 
        border: 'none',
        cursor: 'pointer',
        marginTop: '10px',
        fontSize: '0.9rem', 
        textDecoration: 'underline', 
    },
};
